[WIP]Add game type variables
online-poker/poker-html-client pull request #24
Opened 2017-10-24 12:57 UTC by Mariya-dku

2017-10-24 14:42 UTC, kant2002 requested changes
Комментарии и не забудь пожалуйста про линтинг

2017-10-24 14:42 UTC, kant2002 commented on js/table/tableview.ts
> +    public isTexasHoldemType: KnockoutObservable<boolean>;
Вместо признаков для каждой игры, нам лучше иметь 1 KO Observable - gameType и 2 функции KO computed - has2Cards, has4Cards которые позволят нам добавлять другие варианты покера не прописывая все варианты для каждой игры, и делая те или иные части игры модульно

2017-10-24 14:42 UTC, kant2002 commented on js/table/tableview.ts
> +        if (gameType === 2) {
Это было бы реализовано лучше так
this.gameType = ko.observable(3);
this.isTexasHoldemType = ko.computed(() => this.gameType() != 2);
this.isOmahaType  = ko.computed(() => this.gameType() == 2);

Тогда просто изменение this.gameType(1) поменяет значения для 2 вычисляемых значений

2017-10-25 10:29 UTC, kant2002 reviewed
Please see comments

2017-10-25 10:29 UTC, kant2002 commented on js/table/cardsHelper.ts
> +function decodeCardsArray(cardsData: string, gameType?: number): number[] {
gameType не должен вообще передаваться как параметр, 4 скрытые карты представленные значением [254, 254, 254, 254] представлены строкой отличной от "/v4=", надо посмотреть какой имеено, аналогично для комбинации когда нет ни одной карты открытой [255, 255, 255, 255]

2017-10-25 13:09 UTC, kant2002 commented on js/table/cardsHelper.ts
> +            cardsData = "WzI1NV1bMjU1XVsyNTVdWzI1NV0=";
use `allNoneFourCards`

2017-10-25 13:09 UTC, kant2002 commented on js/table/cardsHelper.ts
> +    if (cardsData === "WzI1NV1bMjU1XVsyNTVdWzI1NV0=") {
use `allNoneFourCards`

2017-10-26 07:47 UTC, kant2002 commented on js/table/tablemanager.ts
> +            allNoneClasses = gameType === 1 ? allNoneClasses : ["cards back", "cards back", "cards back", "cards back"];
тут должны быть классы "cards none" и также хорошо было бы использовать константы вместо зашитых значений

2017-10-26 11:12 UTC, kant2002 commented on js/table/cardsHelper.ts
> +let allBacksClasses = ["cards back", "cards back"];
Сделай новую константу allBacksClassesTwoCards которая будет предсталвять собой фиксированный массив c закрытыми картами

2017-10-26 11:13 UTC, kant2002 commented on js/table/cardsHelper.ts
> +let allBacksClassesFourCards = ["cards back", "cards back", "cards back", "cards back"];
Значение allBacksClassesFourCards надо обїявить как константу

2017-10-26 11:24 UTC, Mariya-dku commented on js/table/cardsHelper.ts
> +let allBacksClasses = ["cards back", "cards back"];
Почему нужно использовать allBacksClassesTwoCards? я думала в TableManager менять значение allBacksClasses они будут равны или allBacksClassesTwoCards allBacksClassesFourCards, 
тогда все методы и в CardsHelper и в TablePlaceModel будут получать нужные классы, при этом в самих методах изменений не будет

2017-10-26 11:45 UTC, kant2002 commented on js/table/cardsHelper.ts
> +let allBacksClasses = ["cards back", "cards back"];
Потому что нам нужны константы которые явно представляют собой 2 карты. allBaskcClasses изначально надо сделать пустым массивом, и тогда перезаписывание тобой будет иметь смысл когда у нас всего 1 стол. Эта переменная превращается из значения "Закрытые 2 карты" в значение - "текущие значения закрытых карт".

2017-10-26 12:50 UTC, kant2002 commented on js/table/cardsHelper.ts
> +        return ["cards back", "cards back", "cards back", "cards back"];
Используй константы тут и выше

2017-10-26 13:02 UTC, kant2002 approved these changes
LGTM

2017-10-26 13:07 UTC, merged