Use allbackClasses for hand history popup
online-poker/poker-html-client pull request #26
Opened 2017-10-27 11:44 UTC by Mariya-dku

2017-10-27 15:45 UTC, kant2002 requested changes

2017-10-27 15:45 UTC, kant2002 commented on js/table/handhistory.ts
> +                cards = allBacksClasses;
Эта методика не будет работать, так как если в следующей игре будет другой тип игры, то это окно будет отображать карты для текущей игры. Надо в истории рук хранить какой тип игры, и на основании этого формировать правильное значение для пустых карт

2017-10-28 08:33 UTC, kant2002 commented on js/table/handhistory.ts
> +        gameType: KnockoutObservable<number>) {
Надо передавать number, и чтобы observable значние устанавливается, иначе как раз магия работать не будет, потому что у зависимых KO Computed не будет возможности узнать что `gameType` указывает на другой Observable объект

2017-10-28 08:34 UTC, kant2002 commented on js/table/tablemonitor.ts
> +        gameType: KnockoutObservable<number>) {
Аналогично тому что выше, этот интерфейс нужен для передачи данных. В то время как KO Observable это скорее способ уведомления сторону о том что это значение может меняться динамически, и отправлять изменения о своих значениях

2017-10-28 08:48 UTC, kant2002 commented on js/table/handhistory.ts
> +        this.gameType = ko.observable(gameType);
Нельзя создавать новое KO observable потому что тогда старые Computed которые создавались на основе старого Computed никак не смогут узнать что у него поменялось значение

2017-10-28 08:52 UTC, Mariya-dku commented on js/table/handhistory.ts
> +        this.gameType = ko.observable(gameType);
Я же тут просто задаю новое значение существующей KO observable this.gameType

2017-10-28 08:56 UTC, kant2002 commented on js/table/handhistory.ts
> +        this.gameType = ko.observable(gameType);
Новое значение `this.gameType(gameType)` а ты создаешь новый KO Computed

2017-10-28 09:01 UTC, kant2002 approved these changes

2017-10-28 09:01 UTC, merged