Refactoring to support testing TableView
online-poker/poker-html-client pull request #34
Opened 2017-11-02 00:16 UTC by kant2002

Most changes whcih propagate across codebase is related to importing JS Signals as a module which lead to conversion of modules to CommonJS. One of the module which become converted to CommonJS was cardsHelper which require remove cards globals for closed cards and making them table place specific variables which setup on game type change.

2017-11-02 04:41 UTC, Mariya-dku commented
Текущие ошибки в консоле игрока:
1. ```Uncaught ReferenceError: signals is not defined
    at new App (application.js:14936)
    at bootstrap (application.js:16936)
    at Object.<anonymous> (application.js:17000)
    at Object.execCb (require.js:1658)
    at Module.check (require.js:874)
    at Module.<anonymous> (require.js:1121)
    at require.js:132
    at require.js:1164
    at each (require.js:57)
    at Module.emit (require.js:1163)```
2. ```Bind popup tableMenu failed```
3. ```Detailed exception:  ReferenceError: Unable to process binding "if: function (){return allowTickets }"
Message: Unable to process binding "ltext: function (){return standupText }"
Message: app is not defined
    at application.js:4854
    at Function.Uc (knockout-3.4.2.js:52)
    at Function.Vc (knockout-3.4.2.js:51)
    at Function.U (knockout-3.4.2.js:51)
    at Function.ua (knockout-3.4.2.js:53)
    at Function.Y (knockout-3.4.2.js:36)
    at Function.yc (knockout-3.4.2.js:50)
    at Object.W (knockout-3.4.2.js:8)
    at Object.sc (knockout-3.4.2.js:40)
    at e (knockout-3.4.2.js:48)```

2017-11-03 04:29 UTC, mtutynina requested changes
За столом два игрока, один в статусе отошел - меняем тип игры на омаху, обновляем страницу, получаем ошибку 
```
TypeError: Cannot read property 'reduce' of null
    at ActionBlock.getPot (application.js:8076)
    at TableView.<anonymous> (application.js:8951)
    at Function.Uc (knockout-3.4.2.js:52)
    at Function.Vc (knockout-3.4.2.js:51)
    at Function.U (knockout-3.4.2.js:51)
    at Function.ec (knockout-3.4.2.js:50)
    at Function.notifySubscribers (knockout-3.4.2.js:37)
    at Function.ha (knockout-3.4.2.js:41)
    at TableView.c [as pots] (knockout-3.4.2.js:40)
    at TableView.onTableStatusInfo (application.js:9578)
```

2017-11-03 04:29 UTC, Mariya-dku commented on js/table/gameactionsqueue.ts
> +                } catch {
Ошибка в конструкции try catch -> catch(e) из за этого не работает tsc. И почему билд на travis ci проходит? Ты убрал tsc из билда?

2017-11-03 04:29 UTC, Mariya-dku commented on js/table/tableview.ts
> +                place.BackCards(gameType === 1 ? allBacksClassesTwoCards : allBacksClassesFourCards);
При запуске проекта не приходят BackClasses карты на стол, вместо карт просто пусто не важно какой тип игры, при этом после того как один раз сменишь тип игры карты уже приходят или если обновишь страницу.

2017-11-03 04:29 UTC, Mariya-dku commented on js/table/tableview.ts
> +                place.BackCards(gameType === 1 ? allBacksClassesTwoCards : allBacksClassesFourCards);
При этом в консоле игрока после запуска и при смене типа игры не меняются стили, если перезагрузить страницу то в дальнейшем любая смена типа игры отображает верные стили

2017-11-03 07:34 UTC, kant2002 commented on js/table/gameactionsqueue.ts
> +                } catch {
1. Какая у тебя установлена версия tsc?
2. Травис запускает через `npm run compile`

2017-11-03 07:36 UTC, Mariya-dku commented on js/table/gameactionsqueue.ts
> +                } catch {
tsc Version 2.4.2

2017-11-03 07:38 UTC, kant2002 commented on js/table/gameactionsqueue.ts
> +                } catch {
`npm run compile` локально работает?

2017-11-03 08:05 UTC, Mariya-dku commented on js/table/gameactionsqueue.ts
> +                } catch {
да

2017-11-03 19:39 UTC, merged